adding flux aad pod operator deploment

diff --git a/pipeline.yaml b/pipeline.yaml
--- a/pipeline.yaml
+++ b/pipeline.yaml
@@ -117,13 +117,13 @@ jobs:
       inlineScript: |
         az aks get-credentials --resource-group $(aksResourceGroup) --name $(aksClusterName) --admin
 
-  - task: Bash@3
-    displayName: 'Create Custom Namespaces'
-    inputs:
-      targetType: inline
-      failOnStderr: false
-      script: |
-        kubectl apply -f deployments/namespaces.yaml
+  # - task: Bash@3
+  #   displayName: 'Create Custom Namespaces'
+  #   inputs:
+  #     targetType: inline
+  #     failOnStderr: false
+  #     script: |
+  #       kubectl apply -f deployments/namespaces.yaml
 
   # - task: AzureCLI@1
   #   displayName: 'Bind admin role to "aks-cluster-admin" group'
@@ -173,39 +173,39 @@ jobs:
   #       kubectl apply -f roles/helm-rbac-config.yaml
   #       helm init --wait --service-account tiller --tiller-image gcr.io/kubernetes-helm/tiller:v$(helmVersion) --history-max=5 --kube-context '$(aksClusterName)-admin'
 
-  # - task: Bash@3
-  #   displayName: 'Template repositories.yaml secret'
-  #   inputs:
-  #     targetType: inline
-  #     failOnStderr: true
-  #     script: |
-  #       sed -i -e 's/${ACR_NAME}/$(acrName)/g' \
-  #              -e 's@${ACR_SERVICE_PRINCIPAL_ID}@'"$AKS_SP_ID"'@' \
-  #              -e 's@${ACR_SERVICE_PRINCIPAL_SECRET}@'"$AKS_SP_SECRET"'@' \
-  #         templates/repositories.yaml
-  #   env:
-  #     AKS_SP_ID: $(aksServicePrincipalId)
-  #     AKS_SP_SECRET: $(aksServicePrincipalSecret)
+  - task: Bash@3
+    displayName: 'Template repositories.yaml secret'
+    inputs:
+      targetType: inline
+      failOnStderr: true
+      script: |
+        sed -i -e 's/${ACR_NAME}/$(acrName)/g' \
+               -e 's@${ACR_SERVICE_PRINCIPAL_ID}@'"$AKS_SP_ID"'@' \
+               -e 's@${ACR_SERVICE_PRINCIPAL_SECRET}@'"$AKS_SP_SECRET"'@' \
+          templates/repositories.yaml
+    env:
+      AKS_SP_ID: $(aksServicePrincipalId)
+      AKS_SP_SECRET: $(aksServicePrincipalSecret)
 
-  # - task: Bash@3
-  #   displayName: 'Create repositories.yaml secret'
-  #   inputs:
-  #     targetType: inline
-  #     failOnStderr: false
-  #     script: |
-  #       kubectl -n flux delete secret flux-helm-repositories || true
-  #       kubectl -n flux create secret generic flux-helm-repositories --from-file=templates/repositories.yaml
+  - task: Bash@3
+    displayName: 'Create repositories.yaml secret'
+    inputs:
+      targetType: inline
+      failOnStderr: false
+      script: |
+        kubectl -n flux delete secret flux-helm-repositories || true
+        kubectl -n flux create secret generic flux-helm-repositories --from-file=templates/repositories.yaml
 
-  # - task: Bash@3
-  #   displayName: 'Install Weave Flux'
-  #   inputs:
-  #     targetType: inline
-  #     failOnStderr: false
-  #     script: |
-  #       helm repo add weaveworks https://weaveworks.github.io/flux
-  #       helm upgrade flux weaveworks/flux --install --namespace flux -f deployments/weave-flux/values.yaml \
-  #         --set git.path=k8s/$(aksResourceGroup)-cluster,git.label=$(aksResourceGroup)-cluster \
-  #         --wait
+  - task: Bash@3
+    displayName: 'Install Weave Flux'
+    inputs:
+      targetType: inline
+      failOnStderr: false
+      script: |
+        helm repo add weaveworks https://weaveworks.github.io/flux
+        helm upgrade flux weaveworks/flux --install --namespace admin -f deployments/weave-flux/values.yaml \
+          --set "git.path=k8s/$(aksResourceGroup)-cluster,common",git.label=$(aksResourceGroup)-cluster \
+          --wait
 
   # - task: Bash@3
   #   displayName: 'Template Kured secret'
@@ -274,17 +274,17 @@ jobs:
   #       envsubst < ${IDENTITY_BINDING_PATH} > ${IDENTITY_BINDING_PATH}.tmp && mv ${IDENTITY_BINDING_PATH}.tmp ${IDENTITY_BINDING_PATH}
   #       kubectl apply -f ${IDENTITY_BINDING_PATH}
 
-  - task: Bash@3
-    displayName: 'Deploy KeyVault-FlexVolume $(kvFlexVolumeVersion)'
-    inputs:
-      targetType: inline
-      failOnStderr: false
-      script: |
-        export KV_VERSION=$(kvFlexVolumeVersion)
-        export NAMESPACE_NAME=$(adminNamespace)
-        KV_DEPLOYMENT_PATH='deployments/kv-flexvol-installer.yaml'
-        envsubst < ${KV_DEPLOYMENT_PATH} > ${KV_DEPLOYMENT_PATH}.tmp && mv ${KV_DEPLOYMENT_PATH}.tmp ${KV_DEPLOYMENT_PATH}
-        kubectl apply -f ${KV_DEPLOYMENT_PATH}
+  # - task: Bash@3
+  #   displayName: 'Deploy KeyVault-FlexVolume $(kvFlexVolumeVersion)'
+  #   inputs:
+  #     targetType: inline
+  #     failOnStderr: false
+  #     script: |
+  #       export KV_VERSION=$(kvFlexVolumeVersion)
+  #       export NAMESPACE_NAME=$(adminNamespace)
+  #       KV_DEPLOYMENT_PATH='deployments/kv-flexvol-installer.yaml'
+  #       envsubst < ${KV_DEPLOYMENT_PATH} > ${KV_DEPLOYMENT_PATH}.tmp && mv ${KV_DEPLOYMENT_PATH}.tmp ${KV_DEPLOYMENT_PATH}
+  #       kubectl apply -f ${KV_DEPLOYMENT_PATH}
 
 # - job: RunTests
 #   dependsOn: DeployAKS
